name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: verilator/verilator:latest
    steps:
    - name: Checkout(venus_processor)
      uses: actions/checkout@v3
      with:
        repository: cyanolupus/venus_processor
        path: venus_processor
    - name: Checkout(vasm)
      uses: actions/checkout@v3
      with:
        repository: cyanolupus/vasm
        path: vasm
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Verilator
      run: make -C venus_processor/build/ verilator-build