name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: verilator/verilator:latest
    steps:
    - name: Checkout(venus_processor)
      uses: actions/checkout@v3
    - name: Verilator
      run: make -C build/ verilator-build